FROM openjdk:17-jdk-slim

MAINTAINER lewkoowicz

COPY target/bondProfit-api-0.0.1-SNAPSHOT.jar bondProfit-api-0.0.1-SNAPSHOT.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "bondProfit-api-0.0.1-SNAPSHOT.jar"]